# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - nightly
git:
  depth: 999999
notifications:
  email: false

branches:
  only:
  - master
  - gh-pages # For building documentation
  - /^testing-.*$/ # testing branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

cache:
  directories:
  - $HOME/.julia/artifacts

# Ironic.  He could provide binaries for others but not himself...
addons:
  apt:
    packages:
      - curl
      - wget
      - p7zip-full
      - tar
      - gzip

jobs:
  #allow_failures:
  #  - julia: nightly
  include:
    # Add a job that uses the privileged builder with squashfs shards
    - julia: nightly
      env:
        - BINARYBUILDER_RUNNER=privileged
        - BINARYBUILDER_USE_SQUASHFS=true
        - JULIA_PKG_SERVER=
        - BINARYBUILDER_FULL_SHARD_TEST=true
        - BINARYBUILDER_AUTOMATIC_APPLE=true

    # Add a job that uses the unprivileged builder with unpacked shards
    - julia: nightly
      env:
        - BINARYBUILDER_RUNNER=unprivileged
        - BINARYBUILDER_USE_SQUASHFS=false
        - JULIA_PKG_SERVER=
        - BINARYBUILDER_FULL_SHARD_TEST=true
        - BINARYBUILDER_AUTOMATIC_APPLE=true

    # Add a job that uses the docker builder with unpacked shards
    - julia: nightly
      env:
        - BINARYBUILDER_RUNNER=docker
        - BINARYBUILDER_USE_SQUASHFS=false
        - JULIA_PKG_SERVER=
        - BINARYBUILDER_FULL_SHARD_TEST=true
        - BINARYBUILDER_AUTOMATIC_APPLE=true

    - stage: "Documentation"
      julia: nightly
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

after_success:
 - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
