name: CI

on:
  push:
    branches: "master"
    tags: ["*"]
  pull_request:
  release:

env:
  BINARYBUILDER_FULL_SHARD_TEST: true
  BINARYBUILDER_AUTOMATIC_APPLE: true

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - x64 - runner ${{ matrix.runner }} - SquashFS ${{ matrix.squashfs }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      BINARYBUILDER_RUNNER: ${{ matrix.runner }}
      BINARYBUILDER_USE_SQUASHFS: ${{ matrix.squashfs }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Add a job that uses the privileged builder with squashfs shards
          - runner: privileged
            squashfs: true
            julia-version: "1.7"

          - runner: privileged
            squashfs: true
            julia-version: "nightly"

          # Add a job that uses the unprivileged builder with unpacked shards
          - runner: unprivileged
            squashfs: false
            julia-version: "1.7"

          # Add a job that uses the docker builder with unpacked shards
          - runner: docker
            squashfs: false
            julia-version: "1.7"

    steps:
      - run: sudo rm -rf /opt/*
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: x64
      - uses: julia-actions/cache@v1
        # For the time being cache artifacts only for squashfs, we need too much
        # storage for the unpacked shards
        if: ${{ matrix.squashfs == true }}
        with:
          # Reserve entire cache to artifacts
          cache-name: ${{ matrix.squashfs }}
          cache-artifacts: "true"
          cache-packages: "false"
          cache-registries: "false"
      - uses: julia-actions/julia-buildpkg@latest
      - name: System info
        run: julia --project=. --color=yes -e "using BinaryBuilderBase; BinaryBuilderBase.versioninfo()"
      - name: Setup temporary SSH keys
        run: ssh-keygen -f /home/runner/.ssh/id_rsa -q -N ""
      - name: Run tests
        run: |
          julia --check-bounds=yes --color=yes --depwarn=yes --inline=yes --project=@. -e 'using Pkg; Pkg.instantiate(); Pkg.test(coverage=true)'
      - uses: julia-actions/julia-uploadcodecov@v0.1
        continue-on-error: true
      - uses: julia-actions/julia-uploadcoveralls@v0.1
        continue-on-error: true

  Documentation:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      JULIA_PKG_SERVER: ""
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: "1.7"
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
